name: HubGSelector
version: '${project.version}'
main: org.crafttorch.Handler
api-version: 1.13
authors: [ 2GramsIn ]
description: Craft Torch Gui for all servers
softdepend: [ PlaceholderAPI ]
commands:
  HubGS:
    usage: /<command> reload
    description: Command for reload config
    permission: hubgs.reload
    permission-message: Don't have permission