name: MainLobby
version: '${project.version}'
main: org.crafttorch.Handler
api-version: 1.19
authors: [ 2GramsIn ]
description: Torch Lobby free for all
softdepend: [ PlaceholderAPI ]
commands:
  MainLobby:
    usage: /<command> reload
    description: Command for reload config
    permission: MainLobby.reload
    permission-message: Don't have permission