name: MainLobby
version: '${project.version}'
main: org.crafttorch.Handler
api-version: 1.14
authors: [ 2GramsIn ]
description: Torch Lobby free for all
softdepend: [ PlaceholderAPI ]
commands:
  MainLobby:
    usage: /<command> reload
    description: Command for reload config
    permission: mainlobby.reload
    permission-message: Don't have permission
  shutdown:
    usage: /<command>
    description: shutdowns the server
    permission: mainlobby.shutdown
    permission-message: Don't have permission